<?php

use App\Models\Town;
use Illuminate\Database\Seeder;

class TownsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('towns')->delete();

		$towns = [
			'Abricots',
			'Acul-du-Nord',
			'Anse-à-Foleur',
			'Anse-à-Galets',
			'Anse-à-Pitres',
			'Anse-d\'Hainault',
			'Anse-Rouge',
			'Anse-à-Veau',
			'Aquin',
			'Arcahaie',
			'Arnaud',
			'Arniquet',
			'Autre',
			'Bahon',
			'Baie-de-Henn',
			'Bainet',
			'Baradères',
			'Bas-Limbé',
			'Bassin Bleu',
			'Beaumont',
			'Belladère',
			'Belle-Anse',
			'Bombardopolis',
			'Bonbon',
			'Borgne',
			'Boucan-Carré',
			'Cabaret',
			'Camp-Perrin',
			'Cap-Haïtien',
			'Capotille',
			'Caracol',
			'Carice',
			'Carrefour',
			'Cavaillon',
			'Cayes',
			'Cayes-Jacmel',
			'Cerca-Carvajal',
			'Cerca-la-Source',
			'Chambellan',
			'Chansolme',
			'Chantal',
			'Chardonnières',
			'Cité Soleil',
			'Corail',
			'Cornillon',
			'Coteaux',
			'Côtes-de-Fer',
			'Croix-des-Bouquets',
			'Dame-Marie',
			'Delmas',
			'Desdunes',
			'Dessalines',
			'Dondon',
			'Ennery',
			'Ferrier',
			'Fonds-des-Nègres',
			'Fonds-Verrettes',
			'Fort-Liberté',
			'Ganthier',
			'Gonaïves',
			'Grand-Boucan',
			'Grand-Goâve',
			'Grand-Gosier',
			'Grande-Rivière du Nord',
			'Grande-Saline',
			'Gressier',
			'Gros-Morne',
			'Hinche',
			'Irois',
			'Jacmel',
			'Jean-Rabel',
			'Jérémie',
			'Kenscoff',
			'L\'Asile',
			'L\'Estère',
			'L\'île-à-Vaches',
			'L\'île de la Tortue',
			'La Chappelle',
			'La Vallée-de-Jacmel',
			'La Victoire',
			'Lascahobas',
			'Léogâne',
			'Les Anglais',
			'Limbé',
			'Limonade',
			'Maïssade',
			'Maniche',
			'Marigot',
			'Marmelade',
			'Milot',
			'Miragoâne',
			'Mirebalais',
			'Môle-Saint-Nicolas',
			'Mombin-Crochu',
			'Mont-Organisé',
			'Moron',
			'Ouanaminthe',
			'Paillant',
			'Perches',
			'Pestel',
			'Pétion-Ville',
			'Petit-Goâve',
			'Petit-Trou-de-Nippes',
			'Petite-Rivière-de-l’Artibonite',
			'Petite-Rivière-de-Nippes',
			'Pignon',
			'Pilate',
			'Plaine-du-Nord',
			'Plaisance',
			'Plaisance-de-Nippes',
			'Pointe-à-Raquette',
			'Port-Magot',
			'Port-à-Piment',
			'Port-au-Prince',
			'Port-de-Paix',
			'Port-Salut',
			'Quartier-Morin',
			'Ranquitte',
			'Roche-à-Bateaux',
			'Roseaux',
			'Saint-Louis-du-Nord',
			'Saint-Louis-du-Sud',
			'Saint-Raphaël',
			'Saint-Suzanne',
			'Saint-Marc',
			'Saint-Michel-de-l\'Atalaye',
			'Saut-d\'Eau',
			'Savanette',
			'Saint-Jean-du-Sud',
			'Tabarre',
			'Terre-Neuve',
			'Terrier-Rouge',
			'Thiotte',
			'Thomassique',
			'Thomazeau',
			'Thomonde',
			'Tiburon',
			'Torbeck',
			'Trou-du-Nord',
			'Vallières',
			'Verrettes'
		];

		foreach ($towns as $town) {
			Town::create([
				'name' => $town,
				'slug' => $town
			]);
		}
    }
}
